#+TITLE: Gopher Gaming
#+AUTHOR: Martin Penckert

Minimal TD game written in Go (with the amazing [[https://github.com/faiface/pixel][Pixel]] game library).

* Game Design

** Grid

The playing field is defined as a 2D grid. Monsters will walk on the
grid, coming from left and trying to reach the right side.

Cells on the grid may be blocked, making it necessary for the fiend to
find a way around the obstacle.

If the grid is completely blocked, the player looses all constructions
(there must be at least one viable path for the enemies to reach their
goal).

** Towers

Towers are placed by the player via mouse interaction on the
grid. Towers start shooting at fiends within their range
automatically, favoring the closest fiend. A tower blocks one cell.


** Fiends

Fiends spawn beyond the left limits of the screen and move (in waves)
towards the right side of the screen. They try to find the shortest
path possible and will follow it.

If there is no viable path, all monsters will die and the player
looses all structures (this still rewards money and might be a valid
strategy to rebuild the field).

** Economy

The player gains money for each fiend killed before it passes the right
limits of the screen. Towers (and other structure) cost money.


* TODOs

** Minimal

- [x] UI
  - [x] Show Health
- [x] Fiends spawn randomly on the left side of the screen and start
      traveling to the right
- [x] Fiends reaches right limit of the canvas
  - [x] Reduce Player Health
  - [x] Remove fiends from Game
- [x] Economy
  - [x] Building Towers costs money
  - [x] Killing Fiends rewards money
  - [x] Balance visible in UI
- [x] Canvas (640 x 480 world, however big the window is)
- [ ] Grid
  - [ ] Towers can only be placed on the Grid
  - [x] Fiends follow the Grid
- [ ] Z-index for towers
- [x] Game Over
- [x] Game Restart
  
** Stretch

- [ ] Projectiles
- [ ] Waves
- [ ] Tiles
- [ ] Tiles: tmx support
- [ ] Towers block Grid Cells
  - [ ] Fiends need to find ways around the towers (A*)
- [ ] Show Tower Range
- [ ] Make tower range grid based instead of radius
  - [ ] towers with directions? 
- [ ] Animating fiends in 4 directions
- [ ] Flying Fiends
  - [ ] Shadow
  - [ ] Moved Sprite
- [ ] Swarm behavior (spread and follow)
- [ ] Builder
  - takes time to build towers
  - can only build one tower at a time
- [ ] More Tower Types
  - [ ] Damage as tower property
  - [ ] Barricade: cannot attack, but blocks a cell and is cheap
  - [ ] Mine: money generating tower
